# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pixeldrain < Formula
  desc "Share files with decentralized cloud storage."
  homepage "https://jkawamoto.github.io/go-pixeldrain/"
  version "0.4.0"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/jkawamoto/go-pixeldrain/releases/download/v0.4.0/pd_0.4.0_darwin_amd64.tar.gz"
    sha256 "31c590a9a6c6f412695b28acf56ccec351ea400e30d7a9ba13934ec1d5a93738"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/jkawamoto/go-pixeldrain/releases/download/v0.4.0/pd_0.4.0_linux_amd64.tar.gz"
    sha256 "1a69e061a43b1cb6a8a75c31e66ef3797177633b1f9e245a07c228520d850b96"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/jkawamoto/go-pixeldrain/releases/download/v0.4.0/pd_0.4.0_linux_arm64.tar.gz"
    sha256 "ed4cb53183c6228a63c2151cf50dcfa50502862218fb2b1b76a1d8874a07bb2c"
  end

  def install
    bin.install "pd"
  end
end
