# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pixeldrain < Formula
  desc "Share files with decentralized cloud storage."
  homepage "https://jkawamoto.github.io/go-pixeldrain/"
  version "0.7.3"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/jkawamoto/go-pixeldrain/releases/download/v0.7.3/pd_0.7.3_darwin_amd64.tar.gz"
      sha256 "a6bea95f7d529eb497c88d9c25d2ce0245fa79bf53330b22d0134890684cecfa"

      def install
        bin.install "pd"
      end
    end
    on_arm do
      url "https://github.com/jkawamoto/go-pixeldrain/releases/download/v0.7.3/pd_0.7.3_darwin_arm64.tar.gz"
      sha256 "3dc361b949067d521129a87919de0c6e5e470447ac22ded4206e48cac152975e"

      def install
        bin.install "pd"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jkawamoto/go-pixeldrain/releases/download/v0.7.3/pd_0.7.3_linux_amd64.tar.gz"
        sha256 "1fda5df4ce31adf05e9b3aaf1aa1fd08bfb772bcd6f703fdbadb09722d89a129"

        def install
          bin.install "pd"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/jkawamoto/go-pixeldrain/releases/download/v0.7.3/pd_0.7.3_linux_arm64.tar.gz"
        sha256 "0bccd34a5d097fd033a53231773b21411190db98a5d48d4ef15db1054ab0e881"

        def install
          bin.install "pd"
        end
      end
    end
  end
end
